<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<TargetFramework>net8.0</TargetFramework>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
		</PropertyGroup>

		<ItemGroup>
				<PackageReference Include="Zamin.Core.ApplicationServices" Version="8.0.0" />
		</ItemGroup>

		<ItemGroup>
		  <ProjectReference Include="..\..\..\OvetimePolicies1.SharedKernel\OvetimePolicies1.SharedKernel.csproj" />
		  <ProjectReference Include="..\Contracts\OvetimePolicies1.Core.Contracts.csproj" />
		  <ProjectReference Include="..\Domain\OvetimePolicies1.Core.Domain.csproj" />
		  <ProjectReference Include="..\RequestResponse\OvetimePolicies1.Core.RequestResponse.csproj" />
		</ItemGroup>

</Project>